### PR TITLE
Fix command injection vulnerability

### PR DESCRIPTION
**Pull request by 69**
I've fixed the command injection vulnerability by replacing all instances of `exec` with `execFile` and also removed the `node_modules` folder which must have been committed to the project by accident.

### CODE REVIEW

**Comment by toufik-airane** [comment]
Dear @69,

A lot of files (more than 1610 files) have been removed.
Can you explain why?
Thank you.

**Comment by 69** [comment]
I've removed the node_modules folder as that's not something that should have been commited to the repo in the first place.

**Comment by toufik-airane** [comment]
I understand that you wish to enhance the global quality of the project.
However, we want to focus on the identified security issue.
Can you submit the strict necessary regarding the security issue?

Feel free to submit a PR of the original repository, enhancing the project quality.

**Comment by 69** [comment]
Hey there, I've reverted the commit removing the node_modules folder.

**Comment by JamieSlome** [comment]
We will re-review this pull request next week - thank you for the contribution! 🍰

**Comment by toufik-airane** [comment]
Sorry a bit late. LGTM. 😄

**Review by toufik-airane — APPROVED** [review]

**Comment by CodingNagger** [comment]
Oh just opened a PR to realize you opened one here 8 days ago 🤣

**Comment by toufik-airane** [comment]
Hey @CodingNagger,

We will select and reward the most valuable contribution each Friday.
As soon as we don't have closed the frame to contribute, feel free to open a PR. 👍 
Thanks.

**Comment by huntr-helper** [comment]
Congratulations @69 - your fix has been selected! :tada:<br><br>Thanks for being part of the community & helping secure the world\'s open source code.<br>If you have any questions, please respond in the comments section. Your bounty is on its way - keep hunting!

**Pull request merged**
